import type { CSSProperties } from 'react'
import type { LucideIcon } from 'lucide-react'
import {
  Sparkles,
  Plus,
  LayoutGrid,
  ArrowRight,
  Paperclip,
  BadgeCheck,
  CalendarDays,
  Check,
  ChevronLeft,
  ChevronRight,
  X,
  Bot,
  LayoutDashboard,
  Trash2,
  Download,
  GripVertical,
  Pencil,
  CircleAlert,
  ChevronDown,
  ChevronUp,
  Funnel,
  FunnelX,
  ListFilter,
  Folder,
  MessageSquare,
  Users,
  GitBranch,
  Image,
  Info,
  Lock,
  LogOut,
  Menu,
  EllipsisVertical,
  Bell,
  ExternalLink,
  UserPlus,
  QrCode,
  RefreshCw,
  Send,
  Clock3,
  Search,
  Flag,
  Store,
  Play,
  Pause,
  Mic,
  Video,
  Square,
  KanbanSquare,
  TriangleAlert,
  Layers,
  Star,
  Eye,
  EyeOff,
  Hourglass,
  ClockAlert,
  Maximize2,
  ChevronsLeft,
  ChevronsRight,
  House,
  PhoneCall,
  CheckCheck,
  BarChart3,
  Medal,
  TrendingUp,
  ArrowUp,
  ArrowDown,
  FileText,
  File,
  FileArchive,
  Presentation,
  NotebookText,
  Music,
  Headset,
  ArrowRightCircle,
  Timer,
  List,
  PlusCircle,
  Tag,
  FolderOpen,
  Trophy,
  ZoomIn,
  ZoomOut,
  Minus,
  RefreshCcw,
  SearchCheck,
  CheckCircle,
  Circle,
  ArrowLeftRight,
  Settings2,
  Trash,
  ListChecks,
  MoreHorizontal,
  BellOff,
  Globe,
  Radio,
  Megaphone,
  Shield,
  Copy,
  Mail,
  Settings,
  User,
  ArrowLeft,
  Calendar,
  CheckCircle2,
  Archive,
  Pin,
  Bold,
  Italic,
  ListTodo,
  Table,
  GraduationCap,
  Share2,
  Reply,
  Cloud,
  Activity,
  ClipboardCheck,
  ClipboardList,
  PieChart,
  Target,
  AlertTriangle,
  LineChart,
  Zap,
  XCircle,
  HelpCircle,
  Rocket,
} from 'lucide-react'

interface MaterialSymbolProps {
  name: string
  size?: number
  color?: string
  style?: CSSProperties
  className?: string
}

const ICON_MAP: Record<string, LucideIcon> = {
  bolt: Zap,
  cancel: XCircle,
  help: HelpCircle,
  add: Plus,
  remove: Minus,
  apps: LayoutGrid,
  grid_view: LayoutGrid,
  home: House,
  arrow_forward: ArrowRight,
  arrow_back: ArrowLeft,
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  attach_file: Paperclip,
  auto_awesome: Sparkles,
  auto_fix: Sparkles,
  badge: BadgeCheck,
  calendar_today: CalendarDays,
  calendar_month: Calendar,
  event: CalendarDays,
  check: Check,
  done: Check,
  done_all: CheckCheck,
  check_circle: CheckCircle2,
  check_circle_outline: CheckCircle,
  check_box: CheckCircle2,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  dashboard_customize: LayoutDashboard,
  delete: Trash,
  delete_outline: Trash2,
  download: Download,
  drag_indicator: GripVertical,
  edit: Pencil,
  error: CircleAlert,
  error_outline: CircleAlert,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  arrow_drop_down: ChevronDown,
  insights: LineChart,
  filter_alt: Funnel,
  filter_alt_off: FunnelX,
  filter_list: ListFilter,
  folder: Folder,
  folder_open: FolderOpen,
  forum: MessageSquare,
  contacts: Users,
  group: Users,
  campaign: Megaphone,
  radio: Radio,
  hub: GitBranch,
  account_tree: GitBranch,
  image: Image,
  info: Info,
  lock: Lock,
  logout: LogOut,
  menu: Menu,
  more_vert: EllipsisVertical,
  more_horiz: MoreHorizontal,
  notifications: Bell,
  notifications_none: Bell,
  notifications_off: BellOff,
  open_in_new: ExternalLink,
  person_add: UserPlus,
  person: User,
  public: Globe,
  security: Shield,
  content_copy: Copy,
  pause: Pause,
  play_arrow: Play,
  qr_code: QrCode,
  refresh: RefreshCw,
  autorenew: RefreshCcw,
  reply: Reply,
  send: Send,
  schedule: Clock3,
  search: Search,
  manage_search: SearchCheck,
  sprint: Flag,
  storefront: Store,
  tune: Settings2,
  smart_toy: Bot,
  mic: Mic,
  videocam: Video,
  video_call: PhoneCall,
  call: PhoneCall,
  stop: Square,
  view_kanban: KanbanSquare,
  warning: TriangleAlert,
  'Layer 1': Layers,
  'Layer 2': Layers,
  star: Star,
  star_outline: Star,
  star_border: Star,
  visibility: Eye,
  visibility_off: EyeOff,
  hourglass_top: Hourglass,
  pending_actions: ClockAlert,
  keyboard_double_arrow_left: ChevronsLeft,
  keyboard_double_arrow_right: ChevronsRight,
  qr_code_scanner: QrCode,
  leaderboard: BarChart3,
  analytics: TrendingUp,
  military_tech: Medal,
  rate_review: MessageSquare,
  description: FileText,
  picture_as_pdf: FileText,
  table_chart: Table,
  slideshow: Presentation,
  notes: NotebookText,
  folder_zip: FileArchive,
  insert_drive_file: File,
  audiotrack: Music,
  event_note: FileText,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
  history: ArrowRightCircle,
  timer: Timer,
  list: List,
  view_list: List,
  format_list_bulleted: List,
  add_circle: PlusCircle,
  label: Tag,
  task_alt: BadgeCheck,
  emoji_events: Trophy,
  checklist_rtl: ListChecks,
  sync_alt: ArrowLeftRight,
  mail: Mail,
  settings: Settings,
  radio_button_unchecked: Circle,
  south: ArrowDown,
  movie: Video,
  headset: Headset,
  open_in_full: Maximize2,
  fit_screen: Maximize2,
  archive: Archive,
  keep: Pin,
  push_pin: Pin,
  format_bold: Bold,
  format_italic: Italic,
  checklist: ListTodo,
  school: GraduationCap,
  share: Share2,
  workspace_premium: BadgeCheck,
  verified: BadgeCheck,
  summarize: NotebookText,
  cloud: Cloud,
  monitoring: Activity,
  assignment: ClipboardList,
  assignment_turned_in: ClipboardCheck,
  donut_large: PieChart,
  track_changes: Target,
  history_edu: FileText,
  hourglass_disabled: Hourglass,
  priority_high: AlertTriangle,
  trending_up: LineChart,
  rocket_launch: Rocket,
  data_exploration: TrendingUp,
}

export default function MaterialSymbol({
  name,
  size = 18,
  color = 'currentColor',
  style = {},
  className,
}: MaterialSymbolProps) {
  const Icon = ICON_MAP[name]

  if (Icon) {
    return (
      <Icon
        aria-hidden="true"
        size={size}
        color={color}
        strokeWidth={2}
        className={className}
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          justifyContent: 'center',
          width: size,
          height: size,
          color,
          userSelect: 'none',
          flexShrink: 0,
          ...style,
        }}
      />
    )
  }

  const FallbackIcon = CircleAlert
  return (
    <FallbackIcon
      aria-hidden="true"
      size={size}
      color={color}
      strokeWidth={2}
      className={className}
      style={{
        display: 'inline-flex',
        alignItems: 'center',
        justifyContent: 'center',
        width: size,
        height: size,
        color,
        userSelect: 'none',
        flexShrink: 0,
        ...style,
      }}
    />
  )
}
