import type { Contact, ContactInfoRow, SharedFileRow } from './types'

export const CONTACTS: Contact[] = [
  {
    id: 1,
    name: 'Техническая поддержка',
    sub: 'Начать чат',
    time: '08.01.26',
    avatar: 'ТП',
    seed: 2,
    online: true,
    unread: 0,
    isGroup: false,
    isSupport: true,
    messages: [],
  },
  {
    id: 2,
    name: 'Аскар Абылхайыров',
    sub: 'Видеозвонок',
    time: '14:39',
    avatar: 'АА',
    seed: 0,
    online: true,
    unread: 0,
    isGroup: false,
    isSupport: false,
    messages: [
      { id: 1, from: 'them', text: 'Добрый день! Можете прислать финальный вариант отчёта?', time: '14:10', status: 'read' },
      { id: 2, from: 'me', text: 'Конечно, готовлю сейчас. Отправлю через 30 минут.', time: '14:15', status: 'read' },
      { id: 3, from: 'them', text: 'Спасибо! Жду.', time: '14:18', status: 'read' },
      { id: 4, from: 'me', text: 'Видеозвонок', time: '14:39', status: 'delivered', isCall: true },
    ],
  },
  {
    id: 3,
    name: 'Тамерлан Картаев',
    sub: 'Видеозвонок',
    time: '14:37',
    avatar: 'ТК',
    seed: 3,
    online: false,
    unread: 0,
    isGroup: false,
    isSupport: false,
    messages: [
      { id: 1, from: 'them', text: 'Тамерлан, когда будет готова документация по API?', time: '13:50', status: 'read' },
      { id: 2, from: 'me', text: 'К концу дня всё подготовлю.', time: '14:05', status: 'read' },
      { id: 3, from: 'me', text: 'Видеозвонок', time: '14:37', status: 'delivered', isCall: true },
    ],
  },
  {
    id: 4,
    name: 'Нуржан Сарсенбаев',
    sub: 'test',
    time: 'пт',
    avatar: 'НС',
    seed: 1,
    online: false,
    unread: 0,
    isGroup: false,
    isSupport: false,
    messages: [{ id: 1, from: 'them', text: 'test', time: 'пт', status: 'read' }],
  },
  {
    id: 5,
    name: 'Хамза Кабылбек',
    sub: 'Видеозвонок',
    time: 'чт',
    avatar: 'ХК',
    seed: 0,
    online: true,
    unread: 0,
    isGroup: false,
    isSupport: false,
    messages: [{ id: 1, from: 'me', text: 'Видеозвонок', time: 'чт', status: 'delivered', isCall: true }],
  },
  {
    id: 6,
    name: 'efdf',
    sub: 'Вы: df',
    time: '02.03.26',
    avatar: 'EF',
    seed: 2,
    online: false,
    unread: 0,
    isGroup: false,
    isSupport: false,
    messages: [{ id: 1, from: 'me', text: 'df', time: '02.03.26', status: 'delivered' }],
  },
  {
    id: 7,
    name: 'Саян Аширбеков',
    sub: 'салем',
    time: '27.02.26',
    avatar: 'СА',
    seed: 3,
    online: false,
    unread: 0,
    isGroup: false,
    isSupport: false,
    messages: [{ id: 1, from: 'them', text: 'салем', time: '27.02.26', status: 'read' }],
  },
  {
    id: 8,
    name: 'Команда разработки',
    sub: 'Ибраева: Сборка прошла!',
    time: 'вч',
    avatar: 'КР',
    seed: 1,
    online: false,
    unread: 3,
    isGroup: true,
    isSupport: false,
    messages: [
      { id: 1, from: 'АИ', text: 'Коллеги, новая сборка задеплоена на стейдж.', time: 'вч', status: 'read' },
      { id: 2, from: 'МБ', text: 'Отлично! Проверяю.', time: 'вч', status: 'read' },
      { id: 3, from: 'АИ', text: 'Сборка прошла!', time: 'вч', status: 'read' },
    ],
  },
]

export const CONTACT_INFO_ROWS: ContactInfoRow[] = [
  { icon: 'badge', label: 'Должность', value: 'Главный специалист' },
  { icon: 'corporate_fare', label: 'Отдел', value: 'Цифровые сервисы' },
  { icon: 'alternate_email', label: 'Email', value: 'a.abykhairov@alem.kz' },
  { icon: 'smartphone', label: 'Телефон', value: '+7 701 123 4567' },
]

export const SHARED_FILES: SharedFileRow[] = [
  { name: 'Отчёт Q1 2026.pdf', size: '2.4 MB', icon: 'picture_as_pdf', color: '#C53030' },
  { name: 'Бюджет Q2.xlsx', size: '840 KB', icon: 'table_chart', color: '#0A8F5C' },
]
