export { default as MS } from '../../../shared/ui/MaterialSymbol'
export { default as KpiCard } from './KpiCard'
export { default as ProfileCard } from './ProfileCard'
export { default as NotificationsPanel } from './NotificationsPanel'
export { default as TasksPanel } from './TasksPanel'
export { default as EventsPanel } from './EventsPanel'
export { default as PerformanceCard } from './PerformanceCard'
export { default as ServicesPanel } from './ServicesPanel'
export { DashboardSkeleton } from './Skeletons'
